### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by K-h-Huang** [heartalborada-del/newbingAPI#9]
你好，我没有java相关知识，但是想做个api，能详细介绍下如何使用这个项目的内容吗，或者是用python能实现这种效果吗 ？感谢回复！！！

**Comment by heartalborada-del** [comment]
要拿conversationId的话你要挂梯
这是我博客链接 [https://loliurl.club/531.html](https://loliurl.club/531.html) 只讲了下api
还可以看下issues #2 也有一点api

注意，header最好设置上
``` 
user-agent:  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.24"
x-ms-client-request-id:  RANDOM_uuid
x-ms-useragent:  azsdk-js-api-client-factory/1.0.0-beta.1 core-rest-pipeline/1.10.0 OS/Win32");
```

**Comment by K-h-Huang** [comment]
感谢回复！根据blog我能够拿到我的conversationId，但是具体该怎么使用你的github代码呢，可以给个demo吗，然后blog里面那个Websocket ... 是该如何使用的呢

**Comment by heartalborada-del** [comment]
非常抱歉，才看到你的消息。py应该有ws的库吧,你可以找找

**Comment by heartalborada-del** [comment]
> 感谢回复！根据blog我能够拿到我的conversationId，但是具体该怎么使用你的github代码呢，可以给个demo吗，然后blog里面那个Websocket ... 是该如何使用的呢

demo的话你可以引入包之后照着readme来写(明天上学了，回复可能不及时
